In [1]:
import numpy as np

In [2]:
# creacion de un arreglo de 1 dimension
lista1 = [1, 2, 3, 4, 5]
arreglo1 = np.array(lista1)
arreglo1

array([1, 2, 3, 4, 5])

In [3]:
# verificar tipo de variable
type(arreglo1)

numpy.ndarray

In [4]:
# creacion de un arreglo de 3 dimensiones
lista2=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# lista que puede contener diferentes tipos de datos
lista3 = [1, 2, 3, "4", "b",True]
lista3

[1, 2, 3, '4', 'b', True]

In [6]:
arreglo3 = np.array(lista3)
arreglo3

array(['1', '2', '3', '4', 'b', 'True'], dtype='<U11')

In [8]:
# creacion de lista con puro 0
lista0=np.zeros((5,4))
lista0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# creacion de lista aleatoria de 0 y 1
np.random.random((3,2))

array([[0.3319609 , 0.00477578],
       [0.79685652, 0.31851103],
       [0.14340122, 0.58131252]])

In [10]:
# creacion de lista con rango de valores
np.arange(-2,7)

array([-2, -1,  0,  1,  2,  3,  4,  5,  6])

In [11]:
np.arange(5) # limite superior 5, limite inferior 0

array([0, 1, 2, 3, 4])

In [13]:
# Ejercicio de crear un arreglo multidimensional
arr1=np.array([[1,2],[5,7]])
arr2=np.array([[8,9],[5,7]])
arr3=np.array([[1,2],[5,7]])

In [14]:
arreglo3d = np.array([arr1, arr2, arr3])
arreglo3d

array([[[1, 2],
        [5, 7]],

       [[8, 9],
        [5, 7]],

       [[1, 2],
        [5, 7]]])

In [15]:
lista0=np.zeros((5,4))
lista0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
lista0.shape

(5, 4)

In [17]:
lista2=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arreglo2 = np.array(lista2)
arreglo2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# flatten() convierte un arreglo multidimensional en uno de una sola dimension
arreglo2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arreglo2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# atributo dtype
np.array([1.25,2.43,200.88]).dtype

dtype('float64')

In [23]:
# cambiar el tipo de dato de float64 a float32
arr1=np.array([1.25,2.43,200.88],dtype=np.float32)
arr1.dtype

dtype('float32')

In [24]:
# crear arreglo booleano y luego pasarlo a entero
arr2=np.array([True,False,True])
arr2.dtype

dtype('bool')

In [27]:
# convertir arreglo booleano a entero y entrega 1 si es True y 0 si es False
arrint=arr2.astype(np.int32)
arrint

array([1, 0, 1])

In [28]:
# Homologacion o jerarquizacion de tipos de datos
np.array([0,50,50.8]).dtype

dtype('float64')

In [31]:
np.array([False,42]).dtype
np.array([False,42])

array([ 0, 42])

In [36]:
accidentes = np.array([[0,1,1],[1,0,1],[1,3,2],[2,2,0]])

In [37]:
# suma de todos los accidentes durante 4 años
accidentes.sum()

14

In [38]:
# suma de accidentes por area (columnas)
acc_area = accidentes.sum(axis=0)
acc_area

array([4, 6, 4])

In [39]:
print("Los accidentes por area son: ",acc_area[0])
print("Los accidentes por area son: ",acc_area[1])
print("Los accidentes por area son: ",acc_area[2])

Los accidentes por area son:  4
Los accidentes por area son:  6
Los accidentes por area son:  4


In [40]:
# suma de accidentes por año (filas)
acc_anios = accidentes.sum(axis=1)
acc_anios

array([2, 2, 6, 4])

In [41]:
# conservacion de la forma original
acc_anios = accidentes.sum(axis=1, keepdims=True)
acc_anios

array([[2],
       [2],
       [6],
       [4]])

In [43]:
# numero maximo y minimo de accidentes por año y area
maximo = accidentes.max()
minimo = accidentes.min()
print(f"maximo por accidentes: {maximo}")
print(f"minimo por accidentes: {minimo}")

maximo por accidentes: 3
minimo por accidentes: 0


In [44]:
# promedio de accidentes por año y area
prom=accidentes.mean()
prom

1.1666666666666667

: 

In [6]:
# determine la suma de un arreglo (2x3) mas un numero 3

arre1=np.array([[1,2,3],[4,5,6]])
arre1
dimen=arre1.shape
print(dimen[0])
print(dimen[1])
print(arre1[0][0])

2
3
1


In [8]:
# usando un ciclo
import time
inicio = time.time()

arre0 = np.zeros((2,3))
for renglon in range(dimen[0]):
    for columna in range(dimen[1]):
        arre0[renglon][columna]=arre1[renglon][columna]+3
print(arre0)

fin = time.time()
print(f"tiempo de ejecucion (Segs): {fin-inicio}")

[[4. 5. 6.]
 [7. 8. 9.]]
tiempo de ejecucion (Segs): 0.0010004043579101562


In [9]:
# usando broadcasting o transmision
inicio = time.time()
arre0=arre1+3
print(arre0)

fin = time.time()
print(f"tiempo de ejecucion (Segs): {fin-inicio}")

[[4 5 6]
 [7 8 9]]
tiempo de ejecucion (Segs): 0.0005102157592773438


In [11]:
arr_prod= arre1+3
arr_prod

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
arre1=np.array([[1,2,3],[4,5,6]])
arre2=np.array([[7,8,9],[10,11,12]])
arre3 = arre1+arre2
arre3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [13]:
# comparacion de arreglos con un numero
arre1=np.array([[1,2,3],[4,5,6]])
arre1>2

array([[False, False,  True],
       [ True,  True,  True]])

In [15]:
# comparacion de arreglos con arreglos
letras=np.array(["Numpy","Maneja","Holas","d","e","3"])
len(letras)>5

True

In [17]:
# transformacion para vectorizar la funcion len para comprobar que las palabras tienen mas de 5 letras
letras=np.array(["Numpy","Maneja","Celulares","d","e","3"])
len_vect=np.vectorize(len)
len_vect(letras)>5

array([False,  True,  True, False, False, False])

In [21]:
arre1=np.arange(10).reshape((2,5))
arre1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arre1+np.array([0,1,2,3,4])

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [24]:
arre1=np.arange(10).reshape((2,5))
arre1+np.array([0,1]).reshape((2,1))

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [35]:
arre1=np.arange(15.0).reshape((3,5))
np.flip(arre1)

array([[14., 13., 12., 11., 10.],
       [ 9.,  8.,  7.,  6.,  5.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [34]:
# transposicion de un arreglo
arre1=np.arange(15.0).reshape((3,5))
np.transpose(arre1)


array([[ 0.,  5., 10.],
       [ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.]])

In [38]:
np.array([[1,2],[3,4]])*np.array([[5],
                                 [10]])

array([[ 5, 10],
       [30, 40]])

In [40]:
np.array([[1,2],[3,4]])-np.array([[5,10,]])

array([[-4, -8],
       [-2, -6]])