In [1]:
import numpy as np

In [2]:
# index de un solo elemento
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# extracción de un solo elemento de forma ascendente
x[2]

2

In [4]:
# extracción de un solo elemento de forma descendente
x[-2]

8

In [5]:
x.shape = (2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
x[1, 3]

8

In [7]:
x[1, -1]

9

In [8]:
x[0]

array([0, 1, 2, 3, 4])

In [9]:
x = np.arange(10)
x[1:7:2] # uno al 7 con saltos de 2

array([1, 3, 5])

In [10]:
x[-3:3:-1] # de menos 3 a 3 con saltos de -1

array([7, 6, 5, 4])

In [12]:
x=np.arange(10,1,-1) # de 10 a 1 con saltos de -1
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [14]:
y=np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [15]:
y[np.array([0,2,4]), np.array([0,1,2])] # selecciona los elementos 0,0 2,1 4,2

array([ 0, 15, 30])

In [16]:
# union de arreglos horizontales
arr=np.concatenate(([1,2,3],[4,5,6]))
arr

array([1, 2, 3, 4, 5, 6])

In [17]:
# union de arreglos verticales
np.stack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[1,1,1],[2,2,2]])
np.concatenate((mat1,mat2), axis=0) # union vertical

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [19]:
np.concatenate((mat1,mat2), axis=1) # union horizontal

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [20]:
np.concatenate((mat1,mat2), axis=None) # union unidimensional

array([1, 2, 3, 4, 5, 6, 1, 1, 1, 2, 2, 2])