#### Escribe un programa que mediante indexación en NumPy sea capaz de invertir un arreglo (donde el primer elemento se convierte en el último)

In [2]:
# importar libreria
import numpy as np

In [9]:
# se crea un array del 12 al 20
Orden = np.array([12,13,14,15,16,17,18,19,20])
Orden

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
# se reordena el array de forma descendente
Orden_inver = Orden[::-1]
Orden_inver


array([20, 19, 18, 17, 16, 15, 14, 13, 12])

#### Escribe un programa con NumPy para convertir valores de grados Fahrenheit a grados centigrados. Los valores se almacenan en un arreglo de salida.

In [11]:
Celsius = np.array([0.0 ,12.0 ,45.21 ,34.0 ,99.91 ,32.0])  # se crea un array con los valores de Celsius
print("los valores ingresados son: ",Celsius)
conversion = (Celsius * 1.8) + 32  # se realiza la conversion de Celsius a Farenheit
Farenheit = conversion # se almacena el resultado de la conversion en una variable
print("\nlos valores convertidos de Celsius a Farenheit")
print("son los siguientes: ", Farenheit)

los valores ingresados son:  [ 0.   12.   45.21 34.   99.91 32.  ]

los valores convertidos de Celsius a Farenheit
son los siguientes:  [ 32.     53.6   113.378  93.2   211.838  89.6  ]


In [12]:
# usando la formula descrita en el ejercicio

Celsius = np.array([0.0 ,12.0 ,45.21 ,34.0 ,99.91 ,32.0])
print("los valores ingresados son: ",Celsius)
conversion = (9*Celsius+(32*5))/5
Farenheit = conversion
print("\nlos valores convertidos de Celsius a Farenheit")
print("son los siguientes: ", Farenheit)

los valores ingresados son:  [ 0.   12.   45.21 34.   99.91 32.  ]

los valores convertidos de Celsius a Farenheit
son los siguientes:  [ 32.     53.6   113.378  93.2   211.838  89.6  ]


#### Escribe un programa con NumPy para encontrar la unión de dos arreglos. La unión debe devolver un arreglo ordenado de valores que están en cualquiera de los dos arreglos de entrada (sin repetición).

In [23]:
# Se crean dos arrays con valores numericos
array1 = np.array([10,20,30])
array2 = np.array([20,10,30])

# se realiza la union de los dos arrays, usando la funcion np.union1d
# la cual devuelve los valores unicos de los dos arrays de manera ordenada
salida = np.union1d(array1,array2)
salida

array([10, 20, 30])